grep -Fw -f eu_codes.csv  nm_GEDEvent_v22_1.csv  >  nm_GEDEvent_v22_1.csv_eu
grep -Fw -f eu_codes.csv  nm_GEDEvent_v22_1_processed.csv  >  nm_GEDEvent_v22_1_processed.csv_eu
grep -Fw -f eu_codes.csv  nm_PM25-air-pollution.csv  >  nm_PM25-air-pollution.csv_eu
grep -Fw -f eu_codes.csv  nm_agricultural-area-per-capita.csv  >  nm_agricultural-area-per-capita.csv_eu
grep -Fw -f eu_codes.csv  nm_agricultural-water-withdrawals.csv  >  nm_agricultural-water-withdrawals.csv_eu
grep -Fw -f eu_codes.csv  nm_annual-share-of-co2-emissions.csv  >  nm_annual-share-of-co2-emissions.csv_eu
grep -Fw -f eu_codes.csv  nm_arable-land-use-per-person.csv  >  nm_arable-land-use-per-person.csv_eu
grep -Fw -f eu_codes.csv  nm_area-meadows-and-pastures.csv  >  nm_area-meadows-and-pastures.csv_eu
grep -Fw -f eu_codes.csv  nm_cereal-yield.csv  >  nm_cereal-yield.csv_eu
grep -Fw -f eu_codes.csv  nm_civil-liberties-score-fh.csv  >  nm_civil-liberties-score-fh.csv_eu
grep -Fw -f eu_codes.csv  nm_co-emissions-per-capita.csv  >  nm_co-emissions-per-capita.csv_eu
grep -Fw -f eu_codes.csv  nm_co2-emissions-per-country.csv  >  nm_co2-emissions-per-country.csv_eu
grep -Fw -f eu_codes.csv  nm_economic-inequality-gini-index.csv  >  nm_economic-inequality-gini-index.csv_eu
grep -Fw -f eu_codes.csv  nm_electricity-renewables_share.csv  >  nm_electricity-renewables_share.csv_eu
grep -Fw -f eu_codes.csv  nm_electricity-renewables_twt.csv  >  nm_electricity-renewables_twt.csv_eu
grep -Fw -f eu_codes.csv  nm_energy-intensity-of-economies.csv  >  nm_energy-intensity-of-economies.csv_eu
grep -Fw -f eu_codes.csv  nm_expected-years-of-schooling.csv  >  nm_expected-years-of-schooling.csv_eu
grep -Fw -f eu_codes.csv  nm_fertilizer-per-ha-of-arable-land.csv  >  nm_fertilizer-per-ha-of-arable-land.csv_eu
grep -Fw -f eu_codes.csv  nm_foreign-direct-investment-net-outflows-of-gdp.csv  >  nm_foreign-direct-investment-net-outflows-of-gdp.csv_eu
grep -Fw -f eu_codes.csv  nm_forest-area-as-share-of-land-area.csv  >  nm_forest-area-as-share-of-land-area.csv_eu
grep -Fw -f eu_codes.csv  nm_forest-area-km.csv  >  nm_forest-area-km.csv_eu
grep -Fw -f eu_codes.csv  nm_freedom-of-association.csv  >  nm_freedom-of-association.csv_eu
grep -Fw -f eu_codes.csv  nm_gdp-per-capita-growth.csv  >  nm_gdp-per-capita-growth.csv_eu
grep -Fw -f eu_codes.csv  nm_gdp-per-capita-in-us-dollar-world-bank.csv  >  nm_gdp-per-capita-in-us-dollar-world-bank.csv_eu
grep -Fw -f eu_codes.csv  nm_gdp-per-capita-in-us-dollar-world-bank_growth.csv  >  nm_gdp-per-capita-in-us-dollar-world-bank_growth.csv_eu
grep -Fw -f eu_codes.csv  nm_gross-domestic-product.csv  >  nm_gross-domestic-product.csv_eu
grep -Fw -f eu_codes.csv  nm_gross-domestic-product_growth.csv  >  nm_gross-domestic-product_growth.csv_eu
grep -Fw -f eu_codes.csv  nm_gross-domestic-product_growth_frac.csv  >  nm_gross-domestic-product_growth_frac.csv_eu
grep -Fw -f eu_codes.csv  nm_hadcrut-surface-temperature-anomaly.csv  >  nm_hadcrut-surface-temperature-anomaly.csv_eu
grep -Fw -f eu_codes.csv  nm_happiness-cantril-ladder.csv  >  nm_happiness-cantril-ladder.csv_eu
grep -Fw -f eu_codes.csv  nm_homicide-rate.csv  >  nm_homicide-rate.csv_eu
grep -Fw -f eu_codes.csv  nm_human-development-index.csv  >  nm_human-development-index.csv_eu
grep -Fw -f eu_codes.csv  nm_income-share-of-the-top-10-pip.csv  >  nm_income-share-of-the-top-10-pip.csv_eu
grep -Fw -f eu_codes.csv  nm_land-area-km.csv  >  nm_land-area-km.csv_eu
grep -Fw -f eu_codes.csv  nm_liberal-democracy.csv  >  nm_liberal-democracy.csv_eu
grep -Fw -f eu_codes.csv  nm_life-expectancy.csv  >  nm_life-expectancy.csv_eu
grep -Fw -f eu_codes.csv  nm_mean-years-of-schooling-long-run.csv  >  nm_mean-years-of-schooling-long-run.csv_eu
grep -Fw -f eu_codes.csv  nm_merchandise-exports-gdp-cepii.csv  >  nm_merchandise-exports-gdp-cepii.csv_eu
grep -Fw -f eu_codes.csv  nm_migrant-stock-share.csv  >  nm_migrant-stock-share.csv_eu
grep -Fw -f eu_codes.csv  nm_migration.csv  >  nm_migration.csv_eu
grep -Fw -f eu_codes.csv  nm_military-spending-per-capita.csv  >  nm_military-spending-per-capita.csv_eu
grep -Fw -f eu_codes.csv  nm_nitrogen-fertilizer-application-per-hectare-of-cropland.csv  >  nm_nitrogen-fertilizer-application-per-hectare-of-cropland.csv_eu
grep -Fw -f eu_codes.csv  nm_per-capita-energy-use.csv  >  nm_per-capita-energy-use.csv_eu
grep -Fw -f eu_codes.csv  nm_per-capita-renewables.csv  >  nm_per-capita-renewables.csv_eu
grep -Fw -f eu_codes.csv  nm_pesticide-per-ha-of-cropland.csv  >  nm_pesticide-per-ha-of-cropland.csv_eu
grep -Fw -f eu_codes.csv  nm_phosphate-application-per-hectare-of-cropland.csv  >  nm_phosphate-application-per-hectare-of-cropland.csv_eu
grep -Fw -f eu_codes.csv  nm_plastic-waste-mismanaged.csv  >  nm_plastic-waste-mismanaged.csv_eu
grep -Fw -f eu_codes.csv  nm_population-density.csv  >  nm_population-density.csv_eu
grep -Fw -f eu_codes.csv  nm_population-growth-rates.csv  >  nm_population-growth-rates.csv_eu
grep -Fw -f eu_codes.csv  nm_population-growth.csv  >  nm_population-growth.csv_eu
grep -Fw -f eu_codes.csv  nm_population-since-1800.csv  >  nm_population-since-1800.csv_eu
grep -Fw -f eu_codes.csv  nm_potash-fertilizer-application-per-hectare-of-cropland.csv  >  nm_potash-fertilizer-application-per-hectare-of-cropland.csv_eu
grep -Fw -f eu_codes.csv  nm_primary-energy-cons.csv  >  nm_primary-energy-cons.csv_eu
grep -Fw -f eu_codes.csv  nm_red-list-index.csv  >  nm_red-list-index.csv_eu
grep -Fw -f eu_codes.csv  nm_refugee-by-country-of-asylum.csv  >  nm_refugee-by-country-of-asylum.csv_eu
grep -Fw -f eu_codes.csv  nm_refugee-by-country-of-origin.csv  >  nm_refugee-by-country-of-origin.csv_eu
grep -Fw -f eu_codes.csv  nm_research-spending-gdp.csv  >  nm_research-spending-gdp.csv_eu
grep -Fw -f eu_codes.csv  nm_researchers-in-rd-per-million-people.csv  >  nm_researchers-in-rd-per-million-people.csv_eu
grep -Fw -f eu_codes.csv  nm_share-deaths-from-natural-disasters.csv  >  nm_share-deaths-from-natural-disasters.csv_eu
grep -Fw -f eu_codes.csv  nm_trade-as-share-of-gdp.csv  >  nm_trade-as-share-of-gdp.csv_eu
grep -Fw -f eu_codes.csv  nm_ucdp-brd-dyadic-221_code.csv  >  nm_ucdp-brd-dyadic-221_code.csv_eu
grep -Fw -f eu_codes.csv  nm_ucdp-brd-dyadic-221_code_name.csv  >  nm_ucdp-brd-dyadic-221_code_name.csv_eu
grep -Fw -f eu_codes.csv  nm_water-withdrawals-per-capita.csv  >  nm_water-withdrawals-per-capita.csv_eu
grep -Fw -f eu_codes.csv  nmnm_fertilizer-per-ha-of-arable-land.csv  >  nmnm_fertilizer-per-ha-of-arable-land.csv_eu
grep -Fw -f eu_codes.csv  nmnm_mean-years-of-schooling-long-run.csv  >  nmnm_mean-years-of-schooling-long-run.csv_eu
grep -Fw -f eu_codes.csv  nmnm_pesticide-per-ha-of-cropland.csv  >  nmnm_pesticide-per-ha-of-cropland.csv_eu
