mv  nm_GEDEvent_v22_1.csv_eu nm_GEDEvent_v22_1.csv
mv  nm_GEDEvent_v22_1_processed.csv_eu nm_GEDEvent_v22_1_processed.csv
mv  nm_PM25-air-pollution.csv_eu nm_PM25-air-pollution.csv
mv  nm_agricultural-area-per-capita.csv_eu nm_agricultural-area-per-capita.csv
mv  nm_agricultural-water-withdrawals.csv_eu nm_agricultural-water-withdrawals.csv
mv  nm_annual-share-of-co2-emissions.csv_eu nm_annual-share-of-co2-emissions.csv
mv  nm_arable-land-use-per-person.csv_eu nm_arable-land-use-per-person.csv
mv  nm_area-meadows-and-pastures.csv_eu nm_area-meadows-and-pastures.csv
mv  nm_cereal-yield.csv_eu nm_cereal-yield.csv
mv  nm_civil-liberties-score-fh.csv_eu nm_civil-liberties-score-fh.csv
mv  nm_co-emissions-per-capita.csv_eu nm_co-emissions-per-capita.csv
mv  nm_co2-emissions-per-country.csv_eu nm_co2-emissions-per-country.csv
mv  nm_economic-inequality-gini-index.csv_eu nm_economic-inequality-gini-index.csv
mv  nm_electricity-renewables_share.csv_eu nm_electricity-renewables_share.csv
mv  nm_electricity-renewables_twt.csv_eu nm_electricity-renewables_twt.csv
mv  nm_energy-intensity-of-economies.csv_eu nm_energy-intensity-of-economies.csv
mv  nm_expected-years-of-schooling.csv_eu nm_expected-years-of-schooling.csv
mv  nm_fertilizer-per-ha-of-arable-land.csv_eu nm_fertilizer-per-ha-of-arable-land.csv
mv  nm_foreign-direct-investment-net-outflows-of-gdp.csv_eu nm_foreign-direct-investment-net-outflows-of-gdp.csv
mv  nm_forest-area-as-share-of-land-area.csv_eu nm_forest-area-as-share-of-land-area.csv
mv  nm_forest-area-km.csv_eu nm_forest-area-km.csv
mv  nm_freedom-of-association.csv_eu nm_freedom-of-association.csv
mv  nm_gdp-per-capita-growth.csv_eu nm_gdp-per-capita-growth.csv
mv  nm_gdp-per-capita-in-us-dollar-world-bank.csv_eu nm_gdp-per-capita-in-us-dollar-world-bank.csv
mv  nm_gdp-per-capita-in-us-dollar-world-bank_growth.csv_eu nm_gdp-per-capita-in-us-dollar-world-bank_growth.csv
mv  nm_gross-domestic-product.csv_eu nm_gross-domestic-product.csv
mv  nm_gross-domestic-product_growth.csv_eu nm_gross-domestic-product_growth.csv
mv  nm_gross-domestic-product_growth_frac.csv_eu nm_gross-domestic-product_growth_frac.csv
mv  nm_hadcrut-surface-temperature-anomaly.csv_eu nm_hadcrut-surface-temperature-anomaly.csv
mv  nm_happiness-cantril-ladder.csv_eu nm_happiness-cantril-ladder.csv
mv  nm_homicide-rate.csv_eu nm_homicide-rate.csv
mv  nm_human-development-index.csv_eu nm_human-development-index.csv
mv  nm_income-share-of-the-top-10-pip.csv_eu nm_income-share-of-the-top-10-pip.csv
mv  nm_land-area-km.csv_eu nm_land-area-km.csv
mv  nm_liberal-democracy.csv_eu nm_liberal-democracy.csv
mv  nm_life-expectancy.csv_eu nm_life-expectancy.csv
mv  nm_mean-years-of-schooling-long-run.csv_eu nm_mean-years-of-schooling-long-run.csv
mv  nm_merchandise-exports-gdp-cepii.csv_eu nm_merchandise-exports-gdp-cepii.csv
mv  nm_migrant-stock-share.csv_eu nm_migrant-stock-share.csv
mv  nm_migration.csv_eu nm_migration.csv
mv  nm_military-spending-per-capita.csv_eu nm_military-spending-per-capita.csv
mv  nm_nitrogen-fertilizer-application-per-hectare-of-cropland.csv_eu nm_nitrogen-fertilizer-application-per-hectare-of-cropland.csv
mv  nm_per-capita-energy-use.csv_eu nm_per-capita-energy-use.csv
mv  nm_per-capita-renewables.csv_eu nm_per-capita-renewables.csv
mv  nm_pesticide-per-ha-of-cropland.csv_eu nm_pesticide-per-ha-of-cropland.csv
mv  nm_phosphate-application-per-hectare-of-cropland.csv_eu nm_phosphate-application-per-hectare-of-cropland.csv
mv  nm_plastic-waste-mismanaged.csv_eu nm_plastic-waste-mismanaged.csv
mv  nm_population-density.csv_eu nm_population-density.csv
mv  nm_population-growth-rates.csv_eu nm_population-growth-rates.csv
mv  nm_population-growth.csv_eu nm_population-growth.csv
mv  nm_population-since-1800.csv_eu nm_population-since-1800.csv
mv  nm_potash-fertilizer-application-per-hectare-of-cropland.csv_eu nm_potash-fertilizer-application-per-hectare-of-cropland.csv
mv  nm_primary-energy-cons.csv_eu nm_primary-energy-cons.csv
mv  nm_red-list-index.csv_eu nm_red-list-index.csv
mv  nm_refugee-by-country-of-asylum.csv_eu nm_refugee-by-country-of-asylum.csv
mv  nm_refugee-by-country-of-origin.csv_eu nm_refugee-by-country-of-origin.csv
mv  nm_research-spending-gdp.csv_eu nm_research-spending-gdp.csv
mv  nm_researchers-in-rd-per-million-people.csv_eu nm_researchers-in-rd-per-million-people.csv
mv  nm_share-deaths-from-natural-disasters.csv_eu nm_share-deaths-from-natural-disasters.csv
mv  nm_trade-as-share-of-gdp.csv_eu nm_trade-as-share-of-gdp.csv
mv  nm_ucdp-brd-dyadic-221_code.csv_eu nm_ucdp-brd-dyadic-221_code.csv
mv  nm_ucdp-brd-dyadic-221_code_name.csv_eu nm_ucdp-brd-dyadic-221_code_name.csv
mv  nm_water-withdrawals-per-capita.csv_eu nm_water-withdrawals-per-capita.csv
mv  nmnm_fertilizer-per-ha-of-arable-land.csv_eu nmnm_fertilizer-per-ha-of-arable-land.csv
mv  nmnm_mean-years-of-schooling-long-run.csv_eu nmnm_mean-years-of-schooling-long-run.csv
mv  nmnm_pesticide-per-ha-of-cropland.csv_eu nmnm_pesticide-per-ha-of-cropland.csv
